### PR TITLE
.NET standard support

### PR DESCRIPTION
**Pull request by jbogard**

### CODE REVIEW

**Comment by jbogard** [comment]
This lets the solution compile

**Comment by TylerCarlson1** [comment]
So I'm guessing you are OK with having .Net 4.5 and .Net Core have different implementations for performance gain on the 4.5 version then.

**Comment by jbogard** [comment]
Yeah, because eventually AppDomain is coming to .NET Standard. Just not yet.

But it doesn't matter yet, as there are hundreds of failing tests :)

**Comment by TylerCarlson1** [comment]
From what I could tell it's a LONG way to possibly be out, but if it's accepted then that's fine.

**Comment by jbogard** [comment]
So originally I thought I could just support .NET Standard, but if most people do .NET 4.5, why punish them just for people on Xamarin/WinRT? I don't have stats but my gut feel is .NET 4.5 dwarfs the people that use xplat stuff.

The other thing is I've greeeeeeatly reduced the number of #ifdefs because of .NET standard. Like, 2 at this point. Having one or two for perf reasons, that's fine.

**Comment by TylerCarlson1** [comment]
Yea I would say that too about 4.5  That's all I'm going to be using for a good long while.

We'll see how far I get with this.  It's going to provide a whole new challenge to the already challenging world of Expressions Compilation.

**Pull request merged**
